"""
Final phase: materialize the .env files, install systemd units, bring up
docker compose, install/enable bridge + dashboard, run health checks.

Idempotent: re-running re-renders the env files (so rotated keys take
effect) but never duplicates systemd units or compose services.
"""
from __future__ import annotations

import os
import secrets
import shutil
import subprocess
import time
from pathlib import Path

from .ui import ok, warn, info, prompt_yesno, prompt_text


def _write_env_file(path: Path, mapping: dict[str, str], header: str = "") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = []
    if header:
        for ln in header.strip().splitlines():
            lines.append(f"# {ln}")
        lines.append("")
    for k, v in mapping.items():
        if v is None:
            continue
        # Quote values that have spaces.
        if any(c in str(v) for c in " #\"'"):
            v = '"' + str(v).replace('"', '\\"') + '"'
        lines.append(f"{k}={v}")
    path.write_text("\n".join(lines) + "\n")
    try:
        path.chmod(0o600)
    except Exception:
        pass


def _load_env(path: Path) -> dict[str, str]:
    """Parse KEY=VALUE lines of an existing env file (for idempotent re-runs:
    secrets already materialized on disk must survive a wizard re-run even
    when the state file lost them)."""
    out: dict[str, str] = {}
    if not path.exists():
        return out
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        out[k.strip()] = v.strip().strip('"')
    return out


def write_infra_env(state: dict, repo: Path) -> None:
    """Escribe infra/.env (lo consume docker compose: postgres + paperclip).
    Idempotente y preserva valores existentes. IMPORTANTE: se llama ANTES de
    levantar cualquier container — la fase `paperclip` lo invoca antes del
    `docker compose up` (si no, postgres arranca sin POSTGRES_PASSWORD y se
    niega a inicializar), y la fase `services` lo vuelve a llamar para
    completar PAPERCLIP_API_KEY / AICOS_COMPANY_ID ya conocidos tras el
    onboarding."""
    infra_env = repo / "infra" / ".env"
    prev_infra = _load_env(infra_env)
    # Hostnames permitidos para la UI de Paperclip (modo private). Incluimos
    # localhost + todas las IPv4 del host, así si entrás por la IP privada de
    # una VM (p.ej. 192.168.56.50) no te bloquea. Preserva un valor previo.
    host_ips = []
    try:
        out = subprocess.run(["hostname", "-I"], capture_output=True, text=True, timeout=5).stdout
        host_ips = [ip for ip in out.split() if ip.count(".") == 3]
    except Exception:
        pass
    allowed_hosts = prev_infra.get("AICOS_ALLOWED_HOSTNAMES") or ",".join(
        dict.fromkeys(["localhost", "127.0.0.1", *host_ips])
    )
    # NUNCA rotar el password de un Postgres ya inicializado: el volumen
    # conserva el password de initdb y el resto del stack quedaría afuera.
    db_pwd = state.get("postgres_password") or prev_infra.get("POSTGRES_PASSWORD") or secrets.token_urlsafe(20)
    state["postgres_password"] = db_pwd
    auth_secret = (state.get("paperclip_auth_secret")
                   or prev_infra.get("PAPERCLIP_AUTH_SECRET")
                   or secrets.token_urlsafe(32))
    state["paperclip_auth_secret"] = auth_secret
    _write_env_file(infra_env, {
        "POSTGRES_USER":          prev_infra.get("POSTGRES_USER") or "aicos",
        "POSTGRES_PASSWORD":      db_pwd,
        "POSTGRES_DB":            prev_infra.get("POSTGRES_DB") or "aicos",
        "POSTGRES_EXTRA_DBS":     "paperclip",
        "PAPERCLIP_AUTH_SECRET":  auth_secret,
        "AICOS_ALLOWED_HOSTNAMES": allowed_hosts,
        # Dashboard reads Paperclip directly for the live tactical view.
        "PAPERCLIP_API_KEY":      state.get("paperclip_api_key") or prev_infra.get("PAPERCLIP_API_KEY", ""),
        "AICOS_COMPANY_ID":       state.get("company_id") or prev_infra.get("AICOS_COMPANY_ID", ""),
        "AICOS_HERMES_AGENT_ID":  state.get("hermes_agent_id") or prev_infra.get("AICOS_HERMES_AGENT_ID", ""),
        # Paperclip container mounts the host home at the same path so
        # process-adapter cwd values resolve identically (Path A).
        "AICOS_HOST_HOME":        str(Path.home()),
        # Caddy proxy (disabled by default; --profile proxy turns it on).
        "AICOS_HOSTNAME":         state.get("public_hostname", "localhost"),
        "AICOS_TLS_EMAIL":        state.get("admin_email", "admin@example.com"),
    }, header="AICOS docker compose env — generated by installer")
    ok(f"wrote {infra_env}")


def _materialize_envs(state: dict, repo: Path) -> None:
    """Write all the env files the stack reads at boot."""
    # 1) infra/.env consumed by docker compose (ya pudo haberlo escrito la fase
    #    paperclip; acá se re-escribe con los datos completos del onboarding).
    write_infra_env(state, repo)

    # 2) Bridge env — systemd unit reads EnvironmentFile=%h/aicos/infra/.env.bridge
    #    (gitignored). Var set mirrors what apps/paperclip-bridge actually reads.
    bridge_env = repo / "infra" / ".env.bridge"
    prev_bridge = _load_env(bridge_env)
    # API keys de CLIs (fase clis) — el bridge propaga su env a los CLI
    # children, así que vivir acá alcanza para claude/codex/agy/opencode.
    cli_keys = {k: v for k, v in (state.get("cli_api_keys") or {}).items() if v}
    # Re-runs: preservar todo lo que ya estaba (keys rotadas a mano, vars
    # extra tipo HERMES_INFERENCE_MODEL) salvo override explícito del wizard.
    _write_env_file(bridge_env, {
        **prev_bridge,
        **cli_keys,
        "BRIDGE_PORT":              prev_bridge.get("BRIDGE_PORT") or "7100",
        "BRIDGE_LOG_LEVEL":         prev_bridge.get("BRIDGE_LOG_LEVEL") or "info",
        "PAPERCLIP_API_URL":        prev_bridge.get("PAPERCLIP_API_URL") or "http://localhost:3100",
        "PAPERCLIP_API_KEY":        state.get("paperclip_api_key") or prev_bridge.get("PAPERCLIP_API_KEY", ""),
        "QUOTA_SERVICE_URL":        prev_bridge.get("QUOTA_SERVICE_URL") or "http://localhost:7001",
        "POLICY_SERVICE_URL":       prev_bridge.get("POLICY_SERVICE_URL") or "http://localhost:7002",
        "LEARNING_SERVICE_URL":     prev_bridge.get("LEARNING_SERVICE_URL") or "http://localhost:7003",
        "GATEWAY_SERVICE_URL":      prev_bridge.get("GATEWAY_SERVICE_URL") or "http://localhost:7004",
        "REDIS_URL":                prev_bridge.get("REDIS_URL") or "redis://localhost:6379",
        "QDRANT_URL":               prev_bridge.get("QDRANT_URL") or "http://localhost:6333",
        # Embeddings locales (claude-only) para la memoria L4 — contenedor
        # text-embeddings-inference (modelo multilingüe 384 dims). El host bridge
        # le pega por el puerto mapeado.
        "AICOS_EMBEDDINGS_URL":     prev_bridge.get("AICOS_EMBEDDINGS_URL") or "http://localhost:7080/embed",
        "AICOS_EMBEDDINGS_DIM":     prev_bridge.get("AICOS_EMBEDDINGS_DIM") or "384",
        # Optional: si querés embeddings por OpenAI en vez del local, seteá esto
        # y borrá AICOS_EMBEDDINGS_URL.
        "OPENAI_API_KEY":           (state.get("openai_api_key") or cli_keys.get("OPENAI_API_KEY")
                                     or prev_bridge.get("OPENAI_API_KEY") or None),
        "AICOS_COMPANY_ID":         state.get("company_id") or prev_bridge.get("AICOS_COMPANY_ID", ""),
        "AICOS_HERMES_AGENT_ID":    state.get("hermes_agent_id") or prev_bridge.get("AICOS_HERMES_AGENT_ID", ""),
        "AICOS_TELEGRAM_SECRET":    state.get("telegram_webhook_secret") or prev_bridge.get("AICOS_TELEGRAM_SECRET") or None,
        "AICOS_DEFAULT_PROJECT_ID": state.get("default_project_id") or prev_bridge.get("AICOS_DEFAULT_PROJECT_ID") or None,
        "BRIDGE_RUN_CONCURRENCY":   prev_bridge.get("BRIDGE_RUN_CONCURRENCY") or "2",
    }, header="AICOS bridge runtime env — generated by installer (NO commitear)")
    ok(f"wrote {bridge_env}")

    # 3) Dashboard env — la unit lo lee via EnvironmentFile=-%h/.config/aicos/dashboard.env
    cfg_dir = Path.home() / ".config" / "aicos"
    cfg_dir.mkdir(parents=True, exist_ok=True)
    dashboard_env = cfg_dir / "dashboard.env"
    prev_dash = _load_env(dashboard_env)
    _write_env_file(dashboard_env, {
        "PORT":                    "3000",
        "QUOTA_SERVICE_URL":       "http://localhost:7001",
        "POLICY_SERVICE_URL":      "http://localhost:7002",
        "LEARNING_SERVICE_URL":    "http://localhost:7003",
        "GATEWAY_SERVICE_URL":     "http://localhost:7004",
        "BRIDGE_SERVICE_URL":      "http://localhost:7100",
        "PAPERCLIP_API_URL":       "http://localhost:3100",
        "PAPERCLIP_API_KEY":       state.get("paperclip_api_key") or prev_dash.get("PAPERCLIP_API_KEY", ""),
        "AICOS_COMPANY_ID":        state.get("company_id") or prev_dash.get("AICOS_COMPANY_ID", ""),
        "AICOS_HERMES_AGENT_ID":   state.get("hermes_agent_id") or prev_dash.get("AICOS_HERMES_AGENT_ID", ""),
        # Strategy Room: la ruta /api/studio/* corre claude DENTRO del container
        # (docker exec) y crea proyectos/tickets vía la API de Paperclip. Necesita
        # el board token, la raíz del repo (para leer el roster) y el home montado.
        "PAPERCLIP_BOARD_TOKEN":   state.get("paperclip_board_token") or prev_dash.get("PAPERCLIP_BOARD_TOKEN", ""),
        "AICOS_ROOT":              str(repo),
        "AICOS_HOST_HOME":         str(Path.home()),
        "AICOS_AGENT_CONTAINER":   "aicos-paperclip",
        "AICOS_DASHBOARD_TOKEN":   (state.get("dashboard_token") or prev_dash.get("AICOS_DASHBOARD_TOKEN")
                                    or secrets.token_urlsafe(24)),
    }, header="AICOS dashboard runtime env — generated by installer")
    state.setdefault("dashboard_token",
                     next((l.split("=",1)[1] for l in dashboard_env.read_text().splitlines()
                           if l.startswith("AICOS_DASHBOARD_TOKEN=")), "").strip('"'))
    ok(f"wrote {dashboard_env}")


# Units that run on the HOST via systemd --user. Everything else (postgres,
# redis, qdrant, paperclip, quota/policy/learning/gateway) runs in docker.
# aicos-quota-manager.service existe como template legacy pero NO se habilita
# (la versión canónica corre en docker).
HOST_UNITS = ["aicos-bridge", "aicos-dashboard"]


def _ensure_local_bin_links(repo: Path) -> None:
    """The systemd units use PATH=%h/.local/bin — make sure node/npm/npx
    resolve there (they usually live inside an nvm dir that systemd doesn't
    know about)."""
    bin_dir = Path.home() / ".local" / "bin"
    bin_dir.mkdir(parents=True, exist_ok=True)
    for tool in ("node", "npm", "npx"):
        src = shutil.which(tool)
        if not src:
            continue
        link = bin_dir / tool
        if link.resolve() == Path(src).resolve():
            continue
        if link.exists() or link.is_symlink():
            link.unlink()
        link.symlink_to(src)
        ok(f"symlinked {link} → {src}")


def _ensure_docker_access() -> None:
    """El dashboard (systemd --user) hace `docker exec` para el chat de la
    Strategy Room. Como systemd --user no hereda el grupo `docker` si el user fue
    agregado después de arrancar el user manager, damos acceso de dos formas:
      - durable: `usermod -aG docker` (efectivo tras relogin/reboot — el user
        manager arranca con el grupo).
      - inmediato: ACL `u:<user>:rw` en /var/run/docker.sock, que el kernel
        evalúa por uid (no por grupo) → el proceso del dashboard entra ya, sin
        reiniciar el user manager (lo cual mataría la sesión del instalador).
    La ACL se pierde si docker reinicia el socket; el grupo cubre post-reboot.
    """
    user = os.environ.get("USER") or ""
    if not user:
        return
    subprocess.run(["sudo", "usermod", "-aG", "docker", user], check=False)
    sock = "/var/run/docker.sock"
    if not Path(sock).exists():
        return
    if shutil.which("setfacl"):
        r = subprocess.run(["sudo", "setfacl", "-m", f"u:{user}:rw", sock],
                           check=False, capture_output=True, text=True)
        if r.returncode == 0:
            ok("acceso al docker socket habilitado para el dashboard (Strategy Room)")
            return
    warn("no pude dar acceso inmediato al docker socket (falta setfacl/acl). El chat de "
         "la Strategy Room va a funcionar después de re-loguear (el grupo docker ya quedó "
         "asignado). Para activarlo ya: `sudo setfacl -m u:$USER:rw /var/run/docker.sock`.")


def _install_systemd_units(state: dict, repo: Path) -> None:
    """Drop the host systemd user units, enable + start."""
    _ensure_docker_access()
    units_src = repo / "infra" / "systemd"
    if not units_src.exists():
        warn(f"systemd templates missing at {units_src} — skipping")
        return
    target = Path.home() / ".config" / "systemd" / "user"
    target.mkdir(parents=True, exist_ok=True)
    for unit in units_src.glob("*.service"):
        dst = target / unit.name
        # systemd resolves %h on its own — plain copy, no templating.
        shutil.copy2(unit, dst)
        ok(f"installed {dst.name}")

    to_enable = list(HOST_UNITS)
    # hermes-gateway: only if Hermes is actually installed.
    if (Path.home() / ".hermes" / "hermes-agent" / "venv").exists():
        to_enable.insert(0, "hermes-gateway")

    # Reload + enable + start
    try:
        subprocess.run(["systemctl", "--user", "daemon-reload"], check=True)
        for svc in to_enable:
            if (target / f"{svc}.service").exists():
                subprocess.run(["systemctl", "--user", "enable", "--now", svc + ".service"], check=True)
                ok(f"enabled+started {svc}")
        # Survive logout: services keep running without an open session.
        subprocess.run(["loginctl", "enable-linger", os.environ.get("USER", "")], check=False)
    except subprocess.CalledProcessError as e:
        warn(f"systemctl --user failed (need --user lingering enabled? `loginctl enable-linger $USER`): {e}")


# Compose services that are canonical in docker. NOTE: aicos-dashboard exists
# in the compose file too, but the canonical dashboard runs on the host via
# systemd (it needs hot access to the bridge on localhost:7100) — bringing it
# up in docker would clash on :3000. Explicit list, never bare `up -d`.
COMPOSE_SERVICES = [
    "postgres", "redis", "qdrant", "embeddings", "paperclip",
    "aicos-quota-manager", "aicos-policy-engine",
    "aicos-tool-gateway", "aicos-learning",
]


def _docker_compose_up(repo: Path) -> None:
    """Bring up the docker side of the stack (infra + paperclip + microservices)."""
    info("Bringing up the docker stack (this builds images on first run — go grab a mate)…")
    subprocess.run(
        ["docker", "compose", "-f", str(repo / "infra" / "docker-compose.yml"),
         "up", "-d", "--remove-orphans", *COMPOSE_SERVICES],
        check=True,
    )


def _healthcheck(state: dict) -> dict:
    """Probe every service. Return summary dict."""
    checks = {
        "Postgres":       ("docker exec aicos-postgres pg_isready -U aicos -d paperclip",      0),
        "Redis":          ("docker exec aicos-redis redis-cli ping",                            0),
        "Qdrant":         ("curl -fsS -m 3 http://localhost:6333/healthz",                     0),
        "Paperclip":      ("curl -fsS -m 3 http://localhost:3100/api/health",                  0),
        "Paperclip UI":   ("curl -fsS -m 3 http://localhost:3100/",                            0),
        "Quota":          ("curl -fsS -m 3 http://localhost:7001/health",                      0),
        "Policy":         ("curl -fsS -m 3 http://localhost:7002/health",                      0),
        "Learning":       ("curl -fsS -m 3 http://localhost:7003/health",                      0),
        "Gateway":        ("curl -fsS -m 3 http://localhost:7004/health",                      0),
        "Bridge":         ("curl -fsS -m 3 http://localhost:7100/health",                      0),
        # SSE nunca cierra: curl sale 28 (timeout) cuando el stream anda.
        # Validamos que el stream emita el evento inicial "connected".
        "Bridge SSE":     ("curl -s -N -m 2 http://localhost:7100/events | head -c 200 | grep -q connected", 0),
        "Bridge /in-flight": ("curl -fsS -m 3 http://localhost:7100/in-flight",                0),
        "Dashboard login":   ("curl -fsS -m 5 http://localhost:3000/login -o /dev/null",       0),
        "Dashboard live preview (/flow)":
            ("curl -fsS -m 5 http://localhost:3000/flow -o /dev/null",                          0),
        # 401 sin token = vivo y con auth enforced (el token está en
        # ~/.config/aicos/dashboard.env) — solo 5xx/timeout es unhealthy.
        "Dashboard flow-state":
            ('code=$(curl -s -o /dev/null -w "%{http_code}" -m 5 http://localhost:3000/api/flow-state); '
             'echo $code | grep -qE "^(200|307|401)$"',                                          0),
    }
    results = {}
    for name, (cmd, expected) in checks.items():
        r = subprocess.run(cmd, shell=True, capture_output=True, text=True)
        passed = r.returncode == expected
        results[name] = passed
        (ok if passed else warn)(f"{name:<10s} {'healthy' if passed else 'NOT healthy'}")
    return results


def _make_bridge_symlink(repo: Path) -> None:
    """
    The bridge ships as plain JS in `apps/paperclip-bridge/dist/index.js`.
    The systemd unit + the docker process adapter both expect to find it
    at ~/.local/bin/aicos-bridge. Create the symlink (idempotent).
    """
    target = repo / "apps" / "paperclip-bridge" / "dist" / "index.js"
    link = Path.home() / ".local" / "bin" / "aicos-bridge"
    link.parent.mkdir(parents=True, exist_ok=True)
    if link.exists() or link.is_symlink():
        link.unlink()
    link.symlink_to(target)
    # Make the dist file executable too (its shebang is #!/usr/bin/env node).
    try:
        target.chmod(0o755)
    except Exception:
        pass
    ok(f"symlinked {link} → {target}")


def _dashboard_standalone_symlinks(repo: Path) -> None:
    """
    Next.js standalone build doesn't auto-include .next/static or public.
    The systemd unit's ExecStartPre symlinks them — but it only runs at
    boot, so if we're starting the unit fresh we want the links present.
    """
    standalone = repo / "apps" / "dashboard" / ".next" / "standalone" / "apps" / "dashboard"
    if not standalone.exists():
        return  # build hasn't produced the standalone tree yet
    standalone.mkdir(parents=True, exist_ok=True)
    for child in (".next/static", "public"):
        src = repo / "apps" / "dashboard" / child
        dst = standalone / child
        if not src.exists():
            continue
        dst.parent.mkdir(parents=True, exist_ok=True)
        if dst.exists() or dst.is_symlink():
            dst.unlink()
        dst.symlink_to(src)


# ── Container egress (salida a internet) ────────────────────────────────────
# Algunos hosts (notablemente WSL2, pero también cualquiera con un docker
# restart raro) dejan la cadena iptables FORWARD en DROP sin las reglas ACCEPT
# de Docker → los containers resuelven DNS pero NO pueden abrir conexiones a
# internet. Resultado: claude/codex/etc corren pero no llegan a sus APIs y
# producen 0 output (timeouts). Lo detectamos y arreglamos.
_EGRESS_TEST_HOST = "api.anthropic.com"


def _container_egress_ok():
    """True/False si pudimos testear; None si no había container listo."""
    test_js = (
        'const h=require("https");'
        f'const r=h.get({{host:"{_EGRESS_TEST_HOST}",path:"/",timeout:6000}},'
        's=>{process.exit(0)});'
        'r.on("timeout",()=>process.exit(1));r.on("error",()=>process.exit(1));'
    )
    for _ in range(20):  # ~40s esperando que paperclip (node) esté exec-able
        probe = subprocess.run(
            ["docker", "exec", "aicos-paperclip", "node", "-e", test_js],
            capture_output=True,
        )
        if probe.returncode in (0, 1):
            return probe.returncode == 0  # 0=egress ok, 1=sin egress
        time.sleep(2)  # 125 = container todavía no listo
    return None


def _apply_forward_fix() -> None:
    subprocess.run(["sudo", "iptables", "-P", "FORWARD", "ACCEPT"], check=False)
    unit = "\n".join([
        "[Unit]",
        "Description=AICOS - restore Docker container egress (FORWARD DROP workaround)",
        "After=docker.service",
        "Requires=docker.service",
        "",
        "[Service]",
        "Type=oneshot",
        "ExecStart=/usr/sbin/iptables -P FORWARD ACCEPT",
        "RemainAfterExit=yes",
        "",
        "[Install]",
        "WantedBy=multi-user.target",
        "",
    ])
    subprocess.run(
        ["sudo", "tee", "/etc/systemd/system/aicos-docker-forward.service"],
        input=unit.encode(), capture_output=True, check=False,
    )
    subprocess.run(["sudo", "systemctl", "daemon-reload"], check=False)
    subprocess.run(
        ["sudo", "systemctl", "enable", "--now", "aicos-docker-forward.service"],
        capture_output=True, check=False,
    )


def _ensure_container_egress() -> None:
    info("Verificando salida a internet de los containers (las IAs necesitan llegar a sus APIs)…")
    res = _container_egress_ok()
    if res is True:
        ok("egress de containers OK")
        return
    if res is None:
        warn("no pude testear el egress (paperclip no respondió). Si las IAs fallan por")
        warn("timeout, corré:  sudo iptables -P FORWARD ACCEPT")
        return
    warn("los containers NO tienen salida a internet — aplicando fix (FORWARD ACCEPT + systemd)…")
    _apply_forward_fix()
    after = _container_egress_ok()
    if after is True:
        ok("egress restaurado y persistente (aicos-docker-forward.service)")
    else:
        warn("egress sigue roto — revisá la red/NAT/iptables del host manualmente")


def configure(state: dict) -> dict:
    repo = Path(state["repo"])

    # 1. Install workspace deps + build every package (the bridge, the
    #    dashboard live preview at /flow, and every microservice).
    info("Installing pnpm workspace deps…")
    try:
        subprocess.run(
            ["pnpm", "install", "--frozen-lockfile"],
            cwd=repo, check=True,
        )
    except subprocess.CalledProcessError:
        warn("frozen-lockfile install failed; retrying with regular install")
        try:
            subprocess.run(["pnpm", "install"], cwd=repo, check=True)
        except subprocess.CalledProcessError as e:
            warn(f"pnpm install failed: {e}")

    # Only the host-side services need a host build — the microservices
    # (quota/policy/gateway/learning) build inside their docker images.
    info("Building host-side packages (bridge + dashboard)…")
    # Next standalone con .next viejo mezcla runtimes y rompe el render
    # ("preloadFont is not a function") — siempre build limpio del dashboard.
    shutil.rmtree(repo / "apps" / "dashboard" / ".next", ignore_errors=True)
    for pkg in ("@aicos/paperclip-bridge", "@aicos/dashboard"):
        r = subprocess.run(["pnpm", "-F", pkg, "build"], cwd=repo, check=False)
        if r.returncode != 0:
            warn(f"build of {pkg} failed — the matching systemd unit won't start until it's fixed")

    # 1b. Materialize the bridge launcher symlink + dashboard standalone links
    #     + node symlinks so systemd can launch them straight after the next step.
    _make_bridge_symlink(repo)
    _dashboard_standalone_symlinks(repo)
    _ensure_local_bin_links(repo)

    # 2. Render env files
    _materialize_envs(state, repo)

    # 3. Bring up docker compose stack
    _docker_compose_up(repo)

    # 3b. Asegurar que los containers tienen salida a internet (las CLIs corren
    #     dentro de Paperclip vía el process adapter y necesitan llegar a sus
    #     APIs). En WSL2/algunos hosts la cadena FORWARD queda en DROP.
    _ensure_container_egress()

    # 4. Install + start systemd units
    _install_systemd_units(state, repo)

    # 5. Wait a moment then health-check
    info("Waiting 10s for services to settle…")
    time.sleep(10)
    results = _healthcheck(state)
    state["healthcheck_results"] = results
    unhealthy = [k for k, v in results.items() if not v]
    if unhealthy:
        warn(f"some services are NOT healthy: {', '.join(unhealthy)}")
        warn("Check `docker ps`, `systemctl --user status aicos-bridge` and try again.")
    else:
        ok("All services healthy")

    state.setdefault("phases_done", []).append("services")
    return state
