"""
Final phase: materialize the .env files, install systemd units, bring up
docker compose, install/enable bridge + dashboard, run health checks.

Idempotent: re-running re-renders the env files (so rotated keys take
effect) but never duplicates systemd units or compose services.
"""
from __future__ import annotations

import os
import secrets
import shutil
import subprocess
import time
from pathlib import Path

from .ui import ok, warn, info, prompt_yesno, prompt_text


def _write_env_file(path: Path, mapping: dict[str, str], header: str = "") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = []
    if header:
        for ln in header.strip().splitlines():
            lines.append(f"# {ln}")
        lines.append("")
    for k, v in mapping.items():
        if v is None:
            continue
        # Quote values that have spaces.
        if any(c in str(v) for c in " #\"'"):
            v = '"' + str(v).replace('"', '\\"') + '"'
        lines.append(f"{k}={v}")
    path.write_text("\n".join(lines) + "\n")
    try:
        path.chmod(0o600)
    except Exception:
        pass


def _materialize_envs(state: dict, repo: Path) -> None:
    """Write all the env files the stack reads at boot."""
    # 1) infra/.env consumed by docker compose
    infra_env = repo / "infra" / ".env"
    db_pwd = state.get("postgres_password") or secrets.token_urlsafe(20)
    state["postgres_password"] = db_pwd
    _write_env_file(infra_env, {
        "POSTGRES_USER":          "aicos",
        "POSTGRES_PASSWORD":      db_pwd,
        "POSTGRES_DB":            "aicos",
        "POSTGRES_EXTRA_DBS":     "paperclip",
        "PAPERCLIP_AUTH_SECRET":  state.get("paperclip_auth_secret") or secrets.token_urlsafe(32),
        # Dashboard reads Paperclip directly for the live tactical view.
        "PAPERCLIP_API_KEY":      state.get("paperclip_api_key", ""),
        "AICOS_COMPANY_ID":       state.get("company_id", ""),
        "AICOS_HERMES_AGENT_ID":  state.get("hermes_agent_id", ""),
        # Caddy proxy (disabled by default; --profile proxy turns it on).
        "AICOS_HOSTNAME":         state.get("public_hostname", "localhost"),
        "AICOS_TLS_EMAIL":        state.get("admin_email", "admin@example.com"),
    }, header="AICOS docker compose env — generated by installer")
    ok(f"wrote {infra_env}")

    # 2) Bridge env (systemd EnvironmentFile)
    bridge_env_dir = Path.home() / ".config" / "aicos"
    bridge_env_dir.mkdir(parents=True, exist_ok=True)
    bridge_env = bridge_env_dir / "bridge.env"
    _write_env_file(bridge_env, {
        "BRIDGE_PORT":              "7100",
        "PAPERCLIP_API_URL":        "http://localhost:3100",
        "PAPERCLIP_API_KEY":        state.get("paperclip_api_key", ""),
        "QUOTA_SERVICE_URL":        "http://localhost:7001",
        "LEARNING_SERVICE_URL":     "http://localhost:7003",
        "POLICY_SERVICE_URL":       "http://localhost:7002",
        "GATEWAY_SERVICE_URL":      "http://localhost:7004",
        "REDIS_URL":                "redis://localhost:6379",
        "AICOS_COMPANY_ID":         state.get("company_id", ""),
        "AICOS_HERMES_AGENT_ID":    state.get("hermes_agent_id", ""),
        "AICOS_TELEGRAM_SECRET":    state.get("telegram_webhook_secret", ""),
        "AICOS_DEFAULT_PROJECT_ID": state.get("default_project_id", ""),
        "BRIDGE_RUN_CONCURRENCY":   "4",
    }, header="AICOS bridge runtime env — generated by installer")
    ok(f"wrote {bridge_env}")

    # 3) Dashboard env (systemd unit reads these via Environment= lines, but we
    #    also drop a sourceable env file for convenience)
    dashboard_env = bridge_env_dir / "dashboard.env"
    _write_env_file(dashboard_env, {
        "PORT":                    "3000",
        "QUOTA_SERVICE_URL":       "http://localhost:7001",
        "POLICY_SERVICE_URL":      "http://localhost:7002",
        "LEARNING_SERVICE_URL":    "http://localhost:7003",
        "GATEWAY_SERVICE_URL":     "http://localhost:7004",
        "BRIDGE_SERVICE_URL":      "http://localhost:7100",
        "PAPERCLIP_API_URL":       "http://localhost:3100",
        "PAPERCLIP_API_KEY":       state.get("paperclip_api_key", ""),
        "AICOS_COMPANY_ID":        state.get("company_id", ""),
        "AICOS_HERMES_AGENT_ID":   state.get("hermes_agent_id", ""),
        "AICOS_DASHBOARD_TOKEN":   state.get("dashboard_token") or secrets.token_urlsafe(24),
    }, header="AICOS dashboard runtime env — generated by installer")
    state.setdefault("dashboard_token",
                     next((l.split("=",1)[1] for l in dashboard_env.read_text().splitlines()
                           if l.startswith("AICOS_DASHBOARD_TOKEN=")), "").strip('"'))
    ok(f"wrote {dashboard_env}")


def _install_systemd_units(state: dict, repo: Path) -> None:
    """Drop the bridge + dashboard systemd user units, enable + start."""
    units_src = repo / "infra" / "systemd"
    if not units_src.exists():
        warn(f"systemd templates missing at {units_src} — skipping")
        return
    target = Path.home() / ".config" / "systemd" / "user"
    target.mkdir(parents=True, exist_ok=True)
    for unit in units_src.glob("*.service"):
        dst = target / unit.name
        # Render: substitute %h placeholder NOT — systemd does that on its own.
        # We just copy.
        shutil.copy2(unit, dst)
        ok(f"installed {dst.name}")

    # Reload + enable + start
    try:
        subprocess.run(["systemctl", "--user", "daemon-reload"], check=True)
        for svc in ("aicos-bridge", "aicos-dashboard"):
            if (target / f"{svc}.service").exists():
                subprocess.run(["systemctl", "--user", "enable", "--now", svc + ".service"], check=True)
                ok(f"enabled+started {svc}")
    except subprocess.CalledProcessError as e:
        warn(f"systemctl --user failed (need --user lingering enabled? `loginctl enable-linger $USER`): {e}")


def _docker_compose_up(repo: Path) -> None:
    """Bring up the full stack."""
    info("Bringing up the full stack via docker compose…")
    subprocess.run(
        ["docker", "compose", "-f", str(repo / "infra" / "docker-compose.yml"),
         "up", "-d", "--remove-orphans"],
        check=True,
    )


def _healthcheck(state: dict) -> dict:
    """Probe every service. Return summary dict."""
    checks = {
        "Postgres":       ("docker exec aicos-postgres pg_isready -U aicos -d paperclip",      0),
        "Redis":          ("docker exec aicos-redis redis-cli ping",                            0),
        "Qdrant":         ("curl -fsS -m 3 http://localhost:6333/healthz",                     0),
        "Paperclip":      ("curl -fsS -m 3 http://localhost:3100/api/health",                  0),
        "Paperclip UI":   ("curl -fsS -m 3 http://localhost:3100/",                            0),
        "Quota":          ("curl -fsS -m 3 http://localhost:7001/health",                      0),
        "Policy":         ("curl -fsS -m 3 http://localhost:7002/health",                      0),
        "Learning":       ("curl -fsS -m 3 http://localhost:7003/health",                      0),
        "Gateway":        ("curl -fsS -m 3 http://localhost:7004/health",                      0),
        "Bridge":         ("curl -fsS -m 3 http://localhost:7100/health",                      0),
        "Bridge SSE":     ("curl -fsS -m 3 -H 'Accept: text/event-stream' "
                           "http://localhost:7100/events --max-time 2 -o /dev/null",            0),
        "Bridge /in-flight": ("curl -fsS -m 3 http://localhost:7100/in-flight",                0),
        "Dashboard login":   ("curl -fsS -m 5 http://localhost:3000/login -o /dev/null",       0),
        "Dashboard live preview (/flow)":
            ("curl -fsS -m 5 http://localhost:3000/flow -o /dev/null",                          0),
        "Dashboard flow-state":
            ("curl -fsS -m 5 http://localhost:3000/api/flow-state -o /dev/null",                0),
    }
    results = {}
    for name, (cmd, expected) in checks.items():
        r = subprocess.run(cmd, shell=True, capture_output=True, text=True)
        passed = r.returncode == expected
        results[name] = passed
        (ok if passed else warn)(f"{name:<10s} {'healthy' if passed else 'NOT healthy'}")
    return results


def _make_bridge_symlink(repo: Path) -> None:
    """
    The bridge ships as plain JS in `apps/paperclip-bridge/dist/index.js`.
    The systemd unit + the docker process adapter both expect to find it
    at ~/.local/bin/aicos-bridge. Create the symlink (idempotent).
    """
    target = repo / "apps" / "paperclip-bridge" / "dist" / "index.js"
    link = Path.home() / ".local" / "bin" / "aicos-bridge"
    link.parent.mkdir(parents=True, exist_ok=True)
    if link.exists() or link.is_symlink():
        link.unlink()
    link.symlink_to(target)
    # Make the dist file executable too (its shebang is #!/usr/bin/env node).
    try:
        target.chmod(0o755)
    except Exception:
        pass
    ok(f"symlinked {link} → {target}")


def _dashboard_standalone_symlinks(repo: Path) -> None:
    """
    Next.js standalone build doesn't auto-include .next/static or public.
    The systemd unit's ExecStartPre symlinks them — but it only runs at
    boot, so if we're starting the unit fresh we want the links present.
    """
    standalone = repo / "apps" / "dashboard" / ".next" / "standalone" / "apps" / "dashboard"
    if not standalone.exists():
        return  # build hasn't produced the standalone tree yet
    standalone.mkdir(parents=True, exist_ok=True)
    for child in (".next/static", "public"):
        src = repo / "apps" / "dashboard" / child
        dst = standalone / child
        if not src.exists():
            continue
        dst.parent.mkdir(parents=True, exist_ok=True)
        if dst.exists() or dst.is_symlink():
            dst.unlink()
        dst.symlink_to(src)


def configure(state: dict) -> dict:
    repo = Path(state["repo"])

    # 1. Install workspace deps + build every package (the bridge, the
    #    dashboard live preview at /flow, and every microservice).
    info("Installing pnpm workspace deps…")
    try:
        subprocess.run(
            ["pnpm", "install", "--frozen-lockfile"],
            cwd=repo, check=True,
        )
    except subprocess.CalledProcessError:
        warn("frozen-lockfile install failed; retrying with regular install")
        try:
            subprocess.run(["pnpm", "install"], cwd=repo, check=True)
        except subprocess.CalledProcessError as e:
            warn(f"pnpm install failed: {e}")

    info("Building every package…")
    for pkg in ("@aicos/paperclip-bridge", "@aicos/dashboard",
                "@aicos/quota-manager", "@aicos/policy-engine",
                "@aicos/tool-gateway", "@aicos/learning"):
        try:
            subprocess.run(["pnpm", "-F", pkg, "build"], cwd=repo, check=False)
        except Exception:
            pass

    # 1b. Materialize the bridge launcher symlink + dashboard standalone links
    #     so systemd can launch them straight after the next step.
    _make_bridge_symlink(repo)
    _dashboard_standalone_symlinks(repo)

    # 2. Render env files
    _materialize_envs(state, repo)

    # 3. Bring up docker compose stack
    _docker_compose_up(repo)

    # 4. Install + start systemd units
    _install_systemd_units(state, repo)

    # 5. Wait a moment then health-check
    info("Waiting 10s for services to settle…")
    time.sleep(10)
    results = _healthcheck(state)
    state["healthcheck_results"] = results
    unhealthy = [k for k, v in results.items() if not v]
    if unhealthy:
        warn(f"some services are NOT healthy: {', '.join(unhealthy)}")
        warn("Check `docker ps`, `systemctl --user status aicos-bridge` and try again.")
    else:
        ok("All services healthy")

    state.setdefault("phases_done", []).append("services")
    return state
